### ISSUE TITLE
Bug: Voyage Calculator Ignoring Daring Tilly

### ISSUE THREAD

**Issue by AeanQuo** [stt-datacore/website#428] opened 2022-12-30 15:02 UTC
After using the Voyage Calculator to determine the optimal crew for a voyage, the indicator for the crew's number in that slot's list always ignores Daring Tilly. This happens regularly, so not a one-time thing.

![IMG_7078](https://user-images.githubusercontent.com/121680384/210083598-d6b39e60-f844-4ef7-9c5a-09fd21caad82.PNG)
The slot for Deputy Science Officer says Lt. Commander Spock and the indicator shows he should be the first option.

![IMG_7077](https://user-images.githubusercontent.com/121680384/210083605-bbe260c4-af1d-4a1e-99fd-ee72e71b0c67.PNG)
However, in the game, the list shows Daring Tilly first.

In addition, since immortalizing her, she's never been a suggested option. Of course, it could just be that her number hasn't been called up, but it does leave the doubt that the calculator is ignoring her for some reason.

**Comment by ussjohnjay** [comment] 2022-12-30 17:43
This has been previously reported and is being investigated. 

Daring Tilly and Lt Cmdr Spock have the same voyage CMD score, which has led to some potential sorting inconsistencies between the game and DataCore. It's likely why DataCore thinks Spock should be shown higher on your crew selection screen than Tilly, but it's not yet clear whether it's affecting the voyage calculation algorithm. (I don't think it is, but I'll look into this further in the next week or so.)

**Comment by AeanQuo** [comment] 2022-12-30 19:25
Oh, sorry. I had looked for it, but didn't see it in the open issues (disclaimer: I didn't go through each, just the ones that looked relevant).

Please let me know if I can be of any help narrowing down the cause of the issue.

**Comment by ussjohnjay** [comment] 2022-12-30 23:47
No worries, I only meant to confirm that this is indeed an issue. It was first reported on our Discord, which of course not everyone checks.

I'll update this thread when the issue is resolved, or if we need more help. Thanks!

**Comment by dtremenak** [comment] 2023-01-22 04:06
In case it's helpful, here's another pair with a tie that sort in the wrong order (Rain Robinson 5/5 and Chef Pike 4/5).

![image](https://user-images.githubusercontent.com/1027848/213899996-fbf39a85-452e-443a-9545-24b498adfb1c.png)
![image](https://user-images.githubusercontent.com/1027848/213900011-0a25b089-a27c-4dd7-a547-e7789d45f686.png)

With attached player data.
[player-data-issue-428.txt](https://github.com/stt-datacore/website/files/10473716/player-data-issue-428.txt)

**Comment by ussjohnjay** [comment] 2023-01-22 20:50
Thanks for the added info! The differences between Pike and Rain here helped narrow down the potential tiebreakers. I'm guessing it might be as simple as crew name, so I'm going to try that.

Feel free to see if the numbers are more accurate on this test site (which also includes some other planned changes to the voyage calculator):
https://voyagecalc-qol23.website-i3mu.pages.dev/playertools?tool=voyage

**Comment by AeanQuo** [comment] 2023-02-03 07:30
I've had the chance to try it a few times thus far and it seems to be sorting properly now.

Loving the options for layout, by the way. Super helpful when multitasking on a phone to set up a voyage.

**Comment by ussjohnjay** [comment] 2023-02-03 15:09
Thanks for the confirmation! I feel pretty good about the latest update, though there's still a chance the sorting may not be 100% correct. If you run into any inconsistencies, please let me know.

Once I get a few more confirmations, I'll move this fix and the layouts to the live site, hopefully by next week. Thanks again for your help!

**Comment by Roykirk1701** [comment] 2023-02-03 18:32
I queued up a voyage yesterday, though I'm not exactly sure at what time.  The bug was still there.  I will continue to monitor, however.

**Comment by AeanQuo** [comment] 2023-02-06 09:11
> I queued up a voyage yesterday, though I'm not exactly sure at what time. The bug was still there. I will continue to monitor, however.

Just to clarify, were you using the live site or the test site that @ussjohnjay had provided earlier? I have yet to encounter the sorting issue on the test site yet.

**Comment by AeanQuo** [comment] 2023-02-06 17:08
I just tested again with the test site and it sorted properly.

Sorry for the long intervals between testing. I only do it when I'm at a computer and my voyages are longer these days -- mostly thanks to your hard work!

**Comment by Roykirk1701** [comment] 2023-02-06 18:22
> Just to clarify, were you using the live site or the test site that @ussjohnjay had provided earlier? I have yet to encounter the sorting issue on the test site yet.

I didn't realize that there was a test site, so I was reporting on production.  I didn't realize it hadn't gone live, so ignore my report.

**Comment by AeanQuo** [comment] 2023-02-13 07:40
While I only get about one voyager per day now (thanks to your hard work!), I've made it a point to use the test site for each over the past week. Haven't run into the sorting bug yet. So, unless someone else sees something, I guess this issue can be closed once the changes go live.

**Comment by ussjohnjay** [comment] 2023-02-27 17:48
The fix to this has now been merged onto the live site along with the latest voyage calculator update. Thanks for everyone's help here!

**Closed by ussjohnjay** 2023-02-27 17:48 UTC
