### ISSUE TITLE
only drawing a blank screen on playertools

### ISSUE THREAD

**Issue by NuvuCika** [stt-datacore/website#243] opened 2021-06-02 17:24 UTC
only drawing a blank screen on playertools

it started on firefox
I tried hard refresh and then explorer and chrome. same result

![Screenshot (392)](https://user-images.githubusercontent.com/84469724/120525150-1b1a6900-c3d8-11eb-8579-d59ffe864cad.png)

[blank screen.txt](https://github.com/stt-datacore/website/files/6586420/blank.screen.txt)

**Comment by AlexCPU** [comment] 2021-06-02 17:28
Duplicate of #233

**Closed by AlexCPU** 2021-06-02 17:28 UTC
