### ISSUE TITLE
Voyage calculator ignores defined exclusions (event crew)

### ISSUE THREAD

**Issue by venimus** [stt-datacore/website#107] opened 2021-03-01 06:38 UTC
![image](https://user-images.githubusercontent.com/632282/109460554-6899d980-7a69-11eb-88a4-31690a2af6af.png)
Didn't do any manual changes, just imported the player data and clicked calculate

**Comment by ineffyble** [comment] 2021-03-01 08:26
I suspect this is specifically an issue with `Q as "God"` caused by the quotation marks breaking things.

**Comment by ussjohnjay** [comment] 2021-11-15 23:51
This should be fixed now.

**Closed by ussjohnjay** 2021-11-15 23:51 UTC
Labels: bug
